name: pyee
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8.3
  - pip=20.2.3
  - flake8=3.8.3
  - mock=4.0.2
  - pytest=6.0.2
  - pytest-asyncio=0.12.0
  - pytest-runner=5.2
  - pytest-trio=0.6.0
  - sphinx=3.2.1
  - tox=3.20.0
  - trio=0.17.0
  - twine=3.2.0
  - twisted=20.3.0
  - vcversioner=2.16.0.0
  - pip:
    - -e .

